name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@main
        with:
          ref: main
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "1405766743@qq.com"
          git config --global user.name "lwen"
          npm install hexo-cli -g
          npm install hexo-cdn-jsdelivr --save
          npm install
          mkdir -p /home/runner/work/lwenxu.github.io/lwenxu.github.io/public
          echo "--------------------------- work dir content ---------------------------"
          ls -l /home/runner/work/lwenxu.github.io/lwenxu.github.io/
          echo "--------------------------- work dir content ---------------------------"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./public # The folder the action should deploy.